"""Rebuild an image by placing regenerated byte ranges into a copy of the original.

A whole-image relink needs original translation-unit boundaries, link order,
and post-link processing that a reconstruction rarely has. The splice is the
honest intermediate: every regenerated range is written at its address into a
copy of the verified original, every uncovered byte is copied and reported as
such, and the result is compared byte-for-byte. The provenance table says what
was regenerated and what was carried over.
"""

load("//decomp:verified_inputs.bzl", "VerifiedFilesInfo")
load("//toolchains/pypy:toolchain.bzl", "PYPY_TOOLCHAIN_TYPE")

_LOCAL_ONLY = {
    "no-remote": "1",
    "no-remote-cache": "1",
    "no-remote-exec": "1",
}

def _image_splice_impl(ctx):
    pypy = ctx.toolchains[PYPY_TOOLCHAIN_TYPE]
    verified = ctx.attr.original[VerifiedFilesInfo]
    files = verified.files.to_list()
    if ctx.attr.original_basename:
        files = [f for f in files if f.basename == ctx.attr.original_basename]
    if len(files) != 1:
        fail("image_splice needs exactly one verified original, found %d" % len(files))
    original = files[0]

    image = ctx.actions.declare_file(ctx.attr.out or ctx.label.name + ".bin")
    provenance = ctx.actions.declare_file(ctx.label.name + ".provenance.tsv")
    report = ctx.actions.declare_file(ctx.label.name + ".report.txt")

    args = ctx.actions.args()
    args.set_param_file_format("multiline")
    args.use_param_file("@%s", use_always = True)
    args.add("--original", original.path)
    args.add("--placements", ctx.file.placements.path)
    args.add("--base-offset", ctx.attr.base_offset)
    args.add("--output", image.path)
    args.add("--provenance", provenance.path)
    args.add("--report", report.path)
    if not ctx.attr.fail_on_mismatch:
        args.add("--allow-mismatch")
    args.add_all(ctx.files.pieces, before_each = "--piece")

    ctx.actions.run(
        executable = pypy.interpreter,
        arguments = ["-B", ctx.file._splicer.path, args],
        inputs = depset(
            direct = [ctx.file._splicer, ctx.file.placements, original, verified.verification] + ctx.files.pieces,
            transitive = [pypy.files],
        ),
        outputs = [image, provenance, report],
        mnemonic = "ImageSplice",
        progress_message = "Splicing regenerated ranges into %s" % original.basename,
        execution_requirements = _LOCAL_ONLY,
        env = {
            "PYTHONDONTWRITEBYTECODE": "1",
            "PYTHONHASHSEED": "0",
        },
    )
    return [
        DefaultInfo(files = depset([image])),
        OutputGroupInfo(
            provenance = depset([provenance]),
            report = depset([report]),
        ),
    ]

image_splice = rule(
    implementation = _image_splice_impl,
    doc = "Place regenerated byte ranges into a copy of a verified original image and compare.",
    attrs = {
        "original": attr.label(providers = [VerifiedFilesInfo], mandatory = True),
        "original_basename": attr.string(doc = "Select one file when the verified target carries several."),
        "placements": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "TSV with a header and rows of offset, length, piece basename.",
        ),
        "pieces": attr.label_list(allow_files = True, doc = "Regenerated byte ranges named in placements."),
        "base_offset": attr.int(default = 0, doc = "File offset that placement offsets are relative to."),
        "fail_on_mismatch": attr.bool(default = True),
        "out": attr.string(doc = "Rebuilt image file name; defaults to <name>.bin."),
        "_splicer": attr.label(
            default = Label("//decomp:splice_image.py"),
            allow_single_file = [".py"],
        ),
    },
    toolchains = [PYPY_TOOLCHAIN_TYPE],
)
