"""Place regenerated byte ranges into a copy of an original image and report provenance."""

import argparse
import csv
import hashlib
import os
import sys
from pathlib import Path


def parse_placements(path):
    placements = []
    with open(path, newline="", encoding="utf-8") as stream:
        reader = csv.DictReader(stream, delimiter="\t")
        required = {"offset", "length", "piece"}
        if not reader.fieldnames or not required.issubset(reader.fieldnames):
            raise ValueError("placements need columns offset, length, piece")
        for row in reader:
            placements.append((int(row["offset"], 0), int(row["length"], 0), row["piece"]))
    placements.sort()
    for (a_off, a_len, a_name), (b_off, _b_len, b_name) in zip(placements, placements[1:]):
        if a_off + a_len > b_off:
            raise ValueError("overlapping placements: %s and %s" % (a_name, b_name))
    return placements


def main():
    parser = argparse.ArgumentParser(description=__doc__, fromfile_prefix_chars="@")
    parser.add_argument("--original", required=True)
    parser.add_argument("--placements", required=True)
    parser.add_argument("--base-offset", type=int, default=0)
    parser.add_argument("--output", required=True)
    parser.add_argument("--provenance", required=True)
    parser.add_argument("--report", required=True)
    parser.add_argument("--allow-mismatch", action="store_true")
    parser.add_argument("--piece", action="append", default=[])
    args = parser.parse_args()

    pieces = {}
    for path in args.piece:
        name = os.path.basename(path)
        if name in pieces:
            raise ValueError("duplicate piece basename: %s" % name)
        pieces[name] = path

    original = Path(args.original).read_bytes()
    rebuilt = bytearray(original)
    placements = parse_placements(args.placements)

    rows = []
    regenerated = 0
    differing = 0
    mismatches = []
    cursor = 0
    for offset, length, name in placements:
        start = args.base_offset + offset
        end = start + length
        if end > len(original):
            raise ValueError("%s extends past the original image" % name)
        if name not in pieces:
            raise ValueError("placement names unknown piece %s" % name)
        data = Path(pieces[name]).read_bytes()
        if len(data) != length:
            raise ValueError("%s is %d bytes; placement expects %d" % (name, len(data), length))
        if start > cursor:
            rows.append((cursor, start, "copied", ""))
        rebuilt[start:end] = data
        regenerated += length
        if data == original[start:end]:
            rows.append((start, end, "regenerated", name))
        else:
            first = next(i for i in range(length) if data[i] != original[start + i])
            differing += length
            mismatches.append("%s at 0x%x: first difference at +0x%x" % (name, start, first))
            rows.append((start, end, "differs", name))
        cursor = end
    if cursor < len(original):
        rows.append((cursor, len(original), "copied", ""))

    Path(args.output).write_bytes(bytes(rebuilt))
    with open(args.provenance, "w", newline="\n", encoding="utf-8") as stream:
        stream.write("start\tend\tkind\tpiece\n")
        for start, end, kind, name in rows:
            stream.write("0x%x\t0x%x\t%s\t%s\n" % (start, end, kind, name))

    copied = len(original) - regenerated
    identical = bytes(rebuilt) == original
    lines = [
        "original=%s" % os.path.basename(args.original),
        "original_sha256=%s" % hashlib.sha256(original).hexdigest(),
        "rebuilt_sha256=%s" % hashlib.sha256(bytes(rebuilt)).hexdigest(),
        "size=%d" % len(original),
        "placements=%d" % len(placements),
        "regenerated_bytes=%d" % regenerated,
        "differing_bytes=%d" % differing,
        "copied_bytes=%d" % copied,
        "identical=%s" % ("true" if identical else "false"),
    ]
    lines.extend("mismatch=%s" % text for text in mismatches)
    Path(args.report).write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    if mismatches and not args.allow_mismatch:
        sys.stderr.write("\n".join(lines) + "\n")
        return 1
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (ValueError, OSError) as error:
        sys.stderr.write("image splice failed: %s\n" % error)
        sys.exit(1)
